name: Publish (CurseForge)

on:
  workflow_dispatch:
    inputs:
      targets:
        description: 'JSON array of {project} objects to publish'
        required: false
        default: '[{"project":"core"}]'
      dry_run:
        type: boolean
        default: false

jobs:
  publish:
    uses: duzos/mod-ci/.github/workflows/publish.yml@v1
    secrets: inherit
    with:
      targets: ${{ inputs.targets }}
      java: '21'
      task: 'publishCurseforge'
      dry_run: ${{ inputs.dry_run }}
